server:
  port: 8085

spring:
  application:
    name: search-service

  # Connect to Elasticsearch
  elasticsearch:
    uris: http://localhost:9200
    connection-timeout: 5s
    socket-timeout: 5s

  # Connect to Kafka
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: search-event-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      # Use String for Keys (Product ID)
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      # Use String for Values (We send JSON strings from the Outbox)
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      # Reliability Settings
      retries: 3
      acks: all

  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 50

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
